### PR TITLE
Upgrade to TypeScript 3.7

### PR DESCRIPTION
**Pull request by amcdnl**

### CODE REVIEW

**Comment by mutsumiya** [comment]
looks like this got the storybook build error too.

**Comment by amcdnl** [comment]
Ya - idk what this one is though :(

**Comment by mutsumiya** [comment]
So based on my investigation, upgrading @babel/core to 7.7.0 causes the storybook build fail, so for now, skipping bael package upgrade seems to be the best, I think.

**Comment by amcdnl** [comment]
Interesting!

**Pull request merged**
